PROJECT_HOME=/Users/rhseeger/Work/typescript-triangle


all: build


clean:
	npm run clean

install:
	# Installs the libraries needed to build
	npm install

build:
	npm run build

run:
	npm run run

test:
	npm run test

.PHONY:	clean build run
